### ISSUE TITLE
Tracking events that occur when no network connection is available are discarded

### ISSUE THREAD

**Issue by roberleitner** [segmentio/Analytics.Xamarin#10]
It appears that any events that occur while the device is offline are discarded. It appears the event queue is being flushed even if the events fail to send to segment.io.

```
[Segment] [DEBUG] Enqueued action in queue. queue size: 1,
[Segment] [DEBUG] Enqueued action in queue. queue size: 1,
[Segment] [DEBUG] Dequeued action in async loop. message id: cb650b22-e5b4-47c3-99d4-c4ed3ac643c0, queue size: 0,
[Segment] [DEBUG] Created flush batch. batch size: 1,
[Segment] [INFO] Sending analytics request to Segment.io .. batch id: c5dc78d7-266e-4a11-a06f-5d4d24aeb9e0, batch size: 1, json size: 651,
[Segment] [ERROR] Request failed batch id: c5dc78d7-266e-4a11-a06f-5d4d24aeb9e0, batch size: 1, json size: 651, reason: One or more errors occurred.,
[Segment] [DEBUG] Queue is empty, flushing is finished.
```

In a server environment this might not be a big deal but on mobile devices which frequently lose connection it seems a more robust queuing strategy is needed.  Other analytics libraries I've used such as Xamarin Insights and Google Analytics have this capability.

**Comment by leankitryan** [comment]
actually, sorry, not even sure this is an issue. please disregard.

**Comment by leankitryan** [comment]
I've gone back and tested this scenario after enabling the Segment Logger. It is in fact an issue.

**Comment by vladik-hbinov** [comment]
Please see if this fix help you
https://github.com/segmentio/Analytics.Xamarin/pull/38

**Comment by vladik-hbinov** [comment]
> > Please see if this fix help you
> > #38
> 
> It fixes the issue, but only if the user doesn't leave the app before the connection come back. I mean there should have a cache or something in Segment 🤔

Maybe it's possible to take the events and store them in local storage or something... Didn't check it.
For now I only added an option to save the events and not throw them away.

**Comment by EmmanuelJego** [comment]
> > > Please see if this fix help you
> > > #38
> > 
> > 
> > It fixes the issue, but only if the user doesn't leave the app before the connection come back. I mean there should have a cache or something in Segment 🤔
> 
> Maybe it's possible to take the events and store them in local storage or something... Didn't check it.
> For now I only added an option to save the events and not throw them away.

I'll do the same. However it is indeed possible to store them in local storage, from your app, since Analytics.Client offers a `Failed` event handler in which you can get the failed event. There you could serialize it, and later deserialize it and try to send it again.
