### ISSUE TITLE
Changes from Analytics 2.0.3 Nuget pacakge are not in GitHub

### ISSUE THREAD

**Issue by danma23** [segmentio/Analytics.Xamarin#11]
The newest version of the Analytics package on nuget is 2.0.3, however that version is not mentioned in the change logs nor have any code changes happened in this repo in awhile.

It looks like the package owner made some local changes and created a new package, but didn't push the code.

**Comment by f2prateek** [comment]
I think you might be looking at the .Net library on nuget and not this one.

**Comment by f2prateek** [comment]
This is the .Net library for reference https://github.com/segmentio/Analytics.NeT

**Comment by f2prateek** [comment]
And yes, you were right, i made the release but did not commit tags to the github repo for analytics.net. Thanks!

**Comment by danma23** [comment]
Ok gotcha, sorry for the confusion! 
Is this library available in a nuget package?

**Comment by f2prateek** [comment]
unfortunately, not currently.

**Comment by danma23** [comment]
Is there a difference between the two projects? At first glance, they look very similar.
 I can land a hand putting this project into a package.

**Comment by f2prateek** [comment]
@danma23 they are indeed similar. the main difference is that this library is meant to be used in client side environments (e.g. Xamarin) while the other one is designed for server side environments. It'd be great to eventually consolidate the codebases.
