### ISSUE TITLE
Also, is it possible to collect campaign and source information on app install event automatically?

### ISSUE THREAD

**Issue by epopov** [segmentio/Analytics.Xamarin#19]
How to collect campaign info like source, name, medium?

**Comment by f2prateek** [comment]
You can send it with the context

https://segment.com/docs/sources/mobile/xamarin/#context

https://segment.com/docs/spec/common/

**Comment by epopov** [comment]
So, Segment Xamarin SDK does not extract these data automatically and does not help with extraction?  I need to use iOS and Android libraries to get these data and add it to the context?

**Comment by f2prateek** [comment]
The iOS and Android libraries don't do this either as far as I remember.


Even *IF* they did (and again, I don't believe they do), you could still use the Xamarin library and send the context fields manually like I suggested.

**Comment by epopov** [comment]
There is a project for iOS that does it for native XCode project https://github.com/segmentio/analytics-ios-iads-attribution

**Comment by f2prateek** [comment]
Yup, though that's only for install attribution. It uses iOS specific APIs and is not available as part of this library.

Again you don't *have* to use that. You can implement it with Xamarin just as easily.

**Comment by epopov** [comment]
I would really appreciate, if you show how to read campaign related data with Xamarin. I can't find any examples.

**Comment by f2prateek** [comment]
Here's the documentation for the ADClient Xamarin API https://developer.xamarin.com/api/type/iAd.ADClient/. To copy the iOS implementation you shared (https://github.com/segmentio/analytics-ios-iads-attribution/blob/master/Analytics-iAds-Attribution/Classes/SEGADTracker.m), you need to register a callback with the ADClient that gives you the attriubtion information using https://developer.xamarin.com/api/member/iAd.ADClient.DetermineAppInstallationAttribution/p/iAd.AttributedToiAdCompletionHandler/.

Then in the callback you can send a track call with that information as properties.

```
#if __IOS__
ADClient.SharedClient.DetermineAppInstallationAttribution(callback)
#endif
```

And then in the callback, send the information you received.
```
Analytics.Client.Track("userId", "Install Attributed", new Properties() {
    { "provider", "iAd" },
    ...
});
```

Xamarin does not seem to provide all the fields that the iOS native API does. So you might have have to write your own wrapper for the iOS native API. If you're unsure, I'd suggest asking on StackOverflow or a Xamarin forum as to how to use https://developer.apple.com/reference/iad/adclient/1614620-requestattributiondetailswithblo.
