### ISSUE TITLE
Support for registering Super Properties

### ISSUE THREAD

**Issue by acrabb** [segmentio/Analytics.Xamarin#23]
Analytics.Xamarin is missing support for registering Super Properties.

**Comment by f2prateek** [comment]
Not sure what you mean, but there is no such thing as super properties in Segment. I've only heard that in the context of Mixpanel - which you send as traits in Segment https://segment.com/docs/integrations/mixpanel/#register-super-properties.

Feel free to write in at https://segment.com/contact if you have follow up questions.

**Comment by acrabb** [comment]
Thanks, yes, I did mean with Mixpanel. It seems that the traits in Segment are not getting registered as Mixpanel Super Properties.
I see the iOS and Android code for Identify registers the traits, but I don't see it in the Xamarin code. Unless they are handled server-side after `Send()` is called with the `Identify` object?

**Comment by f2prateek** [comment]
Please write in via https://segment.com/contact and our success team will help you out.
