### ISSUE TITLE
Why this library ins't in nuget?

### ISSUE THREAD

**Issue by jzeferino** [segmentio/Analytics.Xamarin#26]
Why this library ins't in nuget?

**Comment by f2prateek** [comment]
We haven't gotten around to it.

**Comment by caiofbpa** [comment]
Any news on this? It would be really nice to have this released and maintained on NuGet, like the other .NET packages

**Comment by dlbroadfoot** [comment]
Created PR #34(https://github.com/segmentio/Analytics.Xamarin/pull/34), hopefully they'll merge it in.

**Comment by juliette-ruchel** [comment]
Hi @jzeferino,

Recently a PR modifying the .nuspec file so as to generate a correct nuget package for Analytics.Xamarin so as to be used in old Xamarin applications. A video explaining how to generate the nuget package can be found here:

https://drive.google.com/file/d/1uuz2o8llASlp_SWeo1uChL5rqqDXwgve/view?usp=sharing

However, if your are planning to use .NET Standard 2.0 or start a new Xamaring app we encourage you to use the Segment .NET library which already has support for Xamarin using .NET Standard 2.0. You can check the library in this link:

https://github.com/segmentio/Analytics.NET

Hope you find this information helpful.
