### ISSUE TITLE
Context doesn't include device info : platform, OS version,...

### ISSUE THREAD

**Issue by flchaux** [segmentio/Analytics.Xamarin#32]
I can't get the platform and other important information like the app version on my analytics service. I checked in the segment debugger and I saw these data are not included into the context or anywhere else in the query.

Sample of my query's context:

```
"context": {
    "library": {
      "name": "Analytics.Xamarin",
      "version": "1.0.0"
    },
    "ip": "195.68.37.202"
  }
```

I use the Analytics.Xamarin.Pcl library, MixPanel and Amplitude.

**Comment by f2prateek** [comment]
This is not automatically collected by the Xamarin library, see https://segment.com/docs/spec/common/#context-fields-automatically-collected.
