### ISSUE TITLE
Context doesn't capture "common fields"

### ISSUE THREAD

**Issue by danma23** [segmentio/Analytics.Xamarin#33]
I noticed in the Common Fields section of the documentation, that the Android and iOS versions of the Segment client automatically capture information like device type, OS version, etc:

https://segment.com/docs/spec/common/

For example, here is where the Android client adds all that info to the client:
https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/AnalyticsContext.java

The Xamarin version of the Segment client doesn't capture any of that info:
https://github.com/segmentio/Analytics.Xamarin/blob/master/Analytics.Xamarin.Pcl/Model/Context.cs

Would that info be available in an integration like Mixpanel if it were added to the context?

**Comment by f2prateek** [comment]
If you add it to the context manually, yes this would be available to Mixpanel!
