### ISSUE TITLE
Is posible change  property access to public with private set?. When received track on success event, is not posible access to EventName property.

### ISSUE THREAD

**Issue by agustinvoicemod** [segmentio/Analytics.Xamarin#40]
https://github.com/segmentio/Analytics.Xamarin/blob/0dcf3868f4048be5d942bb1f06381291d86d5ea8/Analytics.Xamarin.Pcl/Model/Track.cs#L15

**Comment by agustinvoicemod** [comment]
Property "Properties" is the same case.

**Comment by juliette-ruchel** [comment]
Hi @agustinvoicemod, we have recently changed that to Public property so you are able to access information of concrete implementations of BaseAction (Track in this case). This change was made in the .NET library of Analytics. It is compatible with Xamarin the library. You can check it out on this link: 
https://github.com/segmentio/Analytics.NET

Or simply look for it in Nuget packages and add it to your project
