### ISSUE TITLE
[Xamarin] Initialization of the SDK doesn't work 

### ISSUE THREAD

**Issue by vincentcastagna** [segmentio/Analytics.Xamarin#48]
Hello,

We are trying to implement your sdk on a xamarin project. 

1 - It is unclear if we must use this repository and build it on our own  (because [this doc](https://segment.com/docs/connections/sources/catalog/libraries/mobile/xamarin/) seem outdated)
2 - Use the [nuget ](https://www.nuget.org/packages/Analytics/) that seem to be built against this project => https://github.com/segmentio/Analytics.NET  

Solution 2 seem to be the right way as it is .NET Standard 2.0 compatible. We installed the NUGET version 3.8.0 on our Xamarin.Android and Xamarin.iOS project.

We called ` Segment.Analytics.Initialize("KEY", new Config().SetAsync(false));` for a test in our `MainActivity.cs` and tried to make a simple call to track data through 
`Segment.Analytics.Client.Track("something", "Navigated to page");.`

But **we don't see anything** in the ouput, telling us if the **initialization failed or succeeded,** which seem odd for a `Initialize `call. 
We don't even see anything in the web client (app.segment.com) of our project, it just stays as "No recent data". 

This is not either due to a delay, because we are trying to make this work since a few days, so if data may take a while to come, it shouldn't take days.

Please, can you advice or point something we may have missed ? 

@juliette-ruchel 
@nd4p90x 

Thanks.

**Comment by nd4p90x** [comment]
@vincentcastagna I will have an Engineer look at this asap.  Thank you.

**Comment by nd4p90x** [comment]
Do you mind elaborating on your setup, are you seeing multiple lost messages?

**Comment by vincentcastagna** [comment]
## Environment
Microsoft Visual Studio Professional 2022
Version 17.0.2
VisualStudio.17.Release/17.0.2+31919.166
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2022   00476-80000-00000-AA620
Microsoft Visual C++ 2022

C# Tools   4.0.1-1.21568.1+6ab6601178d9fba8c680b56934cd1742e0816bff
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Mono Debugging for Visual Studio   17.0.11 (54f19d2)
Support for debugging Mono processes with Visual Studio.

Xamarin   17.0.0.341 (d17-0@ac52790)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.0.0.182 (remotes/origin/d17-0@ea204898d)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.0.17 (9e779b0)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.1.0.5 (d17-0/6b0e6b2)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d17-0@febb1367
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.36.0@a575761
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-0@a5194e9

Xamarin.iOS and Xamarin.Mac SDK   15.2.0.17 (738fde344)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

## Implementation 

- Segment.Analytics.Initialize("KEY", new Config().SetAsync(false));  //Called in MainActivity.cs - OnCreate 
- Segment.Analytics.Client.Track("something", "Navigated to page"); //Called anywhere, for example in a ViewModel 

## Result

We do see analytics being fetched to segment when launching UWP. We do not see anything when launching Android/iOS. 

On Android/iOS we can see something in the ouput when calling `Track`, but don't see anything in segment web app.

[Analytics] [INFO] Sending analytics request to Segment.io .. batch id: 914db74b-866f-40cf-ad57-cc66406fd1a8, json size: 130, batch size: 1,
[Analytics] [INFO] Segment.io request successful. batch id: d05a7051-1687-4b27-9453-56907788a05d, duration (ms): 1010

Don't hesitate if you need more insights, we will provide what we can to help you debug this.

**Comment by imedoc2023** [comment]
Hi @vincentcastagna,

First of all, have you tried adding a function to handle logging? Something like:

Logger.Handlers += Logger_Handlers;

 private static void Logger_Handlers(Logger.Level level, string message, IDictionary<string, object> args)
        {
            //Do something with the received message
           // Console.WriteLine(message);
        }

Also, would you mind telling me where are you looking the Track Message in your app.segment.com workspace?

Perhaps if you look in https://app.segment.com/'your-workspace-name'/sources/net/debugger you can find the messages.

Let me know how if I can help you with something else.

Regards,

Ignacio

**Comment by Marc-Antoine-Soucy** [comment]
We did add the logger. This is the code we added for the logger: 

			Segment.Logger.Handlers += Logging_Handler;

		void Logging_Handler(Level level, string message, IDictionary<string, object> args)
		{
			if (args != null)
			{
				foreach (string key in args.Keys)
				{
					message += String.Format(" {0}: {1},", "" + key, "" + args[key]);
				}
			}
			Console.WriteLine(String.Format("[Analytics] [{0}] {1}", level, message));
		}

And the logger work well, this is how we got the messages: 
[Analytics] [INFO] Sending analytics request to Segment.io .. batch id: 914db74b-866f-40cf-ad57-cc66406fd1a8, json size: 130, batch size: 1,
[Analytics] [INFO] Segment.io request successful. batch id: d05a7051-1687-4b27-9453-56907788a05d, duration (ms): 1010

And the logs seems to tell us it is successful, even when we do it when using an android device. However, we only see information that gets sent by UWP in the debugger.

**Comment by imedoc2023** [comment]
@Marc-Antoine-Soucy Have you tried creating a new Xamarin App in visual studio 2022 and link segment library? Also, have you verified the android device or simulator is connected to Internet when trying to send the track message?

**Comment by Marc-Antoine-Soucy** [comment]
@imedoc2023 I did not try making a new app, but I will try today and keep you updated. But yes, I am sure the android device was connected to the internet.

**Comment by Marc-Antoine-Soucy** [comment]
@imedoc2023 So, I just tried building a new Xamarin app and it does indeed work. I will talk about it with my boss and try to figure out why it's not working in our app early next week. I will keep you updated. Thank you.
