### ISSUE TITLE
Race condition: library keeps throwing TaskCanceledException

### ISSUE THREAD

**Issue by MartinDevillers** [segmentio/Analytics.Xamarin#5]
I have the following code in my `MainActivity.OnCreate`

```
Analytics.Initialize("key goes here");
Analytics.Client.Identify(UserId, null);
Analytics.Client.Failed += (a, e) => System.Diagnostics.Debugger.Break();
```

And a bunch of Track's and Screen's in the rest of my application.

Sometimes, when my app is started, something goes horribly wrong and all events generated by this library silently fail. When this happens, the `Failed` handler is called and I see a `TaskCanceledException` on the passed `Exception` for each event that was supposed to be tracked. Unfortunately, due to the nature of the `TaskCanceledException` there is very little information on where and when this `Exception` occurs. The only useful bit I managed to get out of the debugger is that the `Task` was created using a `TaskFactory` of type `HttpResponseMessage`.

In other cases, the app starts normally and everything works fine! So this seems to be a race-condition. Am I tracking events too soon? Should I wait some predefined period before tracking events?

**Comment by MartinDevillers** [comment]
Took a look at the debug output of Segment by adding the following line in the OnCreate

```
Logger.Handlers += (l, m, a) => System.Diagnostics.Debug.WriteLine("SEGMENT: {0}: {1}", l, m);
```

04-27 12:26:23.703 I/mono-stdout( 3608): SEGMENT: DEBUG: Starting async flush thread ..
04-27 12:26:23.781 I/mono-stdout( 3608): SEGMENT: DEBUG: Queue is empty, flushing is finished.
04-27 12:26:24.117 I/mono-stdout( 3608): SEGMENT: DEBUG: Dequeued action in async loop.
04-27 12:26:24.148 I/mono-stdout( 3608): SEGMENT: DEBUG: Enqueued action in queue.
04-27 12:26:24.179 I/mono-stdout( 3608): SEGMENT: DEBUG: Created flush batch.
04-27 12:26:25.093 I/mono-stdout( 3608): SEGMENT: DEBUG: Enqueued action in queue.
04-27 12:26:25.109 I/mono-stdout( 3608): SEGMENT: DEBUG: Enqueued action in queue.
04-27 12:26:25.132 I/mono-stdout( 3608): SEGMENT: DEBUG: Enqueued action in queue.
04-27 12:26:25.906 I/mono-stdout( 3608): SEGMENT: INFO: Sending analytics request to Segment.io ..
04-27 12:26:27.117 I/mono-stdout( 3608): SEGMENT: DEBUG: Enqueued action in queue.
04-27 12:26:27.187 I/mono-stdout( 3608): SEGMENT: DEBUG: Enqueued action in queue.
04-27 12:26:30.632 I/mono-stdout( 3608): SEGMENT: DEBUG: Enqueued action in queue.
04-27 12:26:30.679 I/mono-stdout( 3608): SEGMENT: DEBUG: Enqueued action in queue.
**04-27 12:26:32.890 I/mono-stdout( 3608): SEGMENT: ERROR: Request failed *debugger breaks***
04-27 12:26:53.718 I/mono-stdout( 3608): SEGMENT: DEBUG: Dequeued action in async loop.
04-27 12:26:53.726 I/mono-stdout( 3608): SEGMENT: DEBUG: Dequeued action in async loop.
04-27 12:26:53.742 I/mono-stdout( 3608): SEGMENT: DEBUG: Dequeued action in async loop.
04-27 12:26:53.757 I/mono-stdout( 3608): SEGMENT: DEBUG: Dequeued action in async loop.
04-27 12:26:53.773 I/mono-stdout( 3608): SEGMENT: DEBUG: Dequeued action in async loop.
04-27 12:26:53.812 I/mono-stdout( 3608): SEGMENT: DEBUG: Dequeued action in async loop.
04-27 12:26:53.828 I/mono-stdout( 3608): SEGMENT: DEBUG: Dequeued action in async loop.
04-27 12:26:53.867 I/mono-stdout( 3608): SEGMENT: DEBUG: Created flush batch.
04-27 12:26:54.289 I/mono-stdout( 3608): SEGMENT: INFO: Sending analytics request to Segment.io ..

**Comment by MartinDevillers** [comment]
Judging by the source code and exception message I'd say this occurs in `BlockingRequestHandler` at

```
var response = _client.SendAsync(request).Result;
```

This may be related to the behavior of the underlying `mono/HttpClient` and the async features created around that,

http://stackoverflow.com/questions/10547895/how-can-i-tell-when-httpclient-has-timed-out

**Comment by f2prateek** [comment]
Thanks for the detailed reports, I'll be able to take e look this week.
