### ISSUE TITLE
If the iOS linker behavior settings are set to Link All the events are not being reported

### ISSUE THREAD

**Issue by vtserej** [segmentio/Analytics.Xamarin#59]
I just found out what was causing the app not to report events in iOS
My assumption is that some fields/methods invoked by reflection are being deleted on app build.
is there a way to fix this, without involving changing the linker behavior.

**Comment by edsonjab** [comment]
Hi @vtserej  we created a new LIB that you can use for your project, [Analytics-CSharp](https://github.com/segmentio/Analytics-CSharp) in this library fixed the issue.
