### ISSUE TITLE
Are there plans for adding in .net6 iOS and Android versions of this project?

### ISSUE THREAD

**Issue by IainS1986** [segmentio/Analytics.Xamarin#62]
This would be for use with MAUI and .net iOS and .net Android native applications that are converting from Xamarin Native  and Xamaring Forms?

**Comment by MichaelGHSeg** [comment]
We have a new library available at https://github.com/segmentio/Analytics-CSharp with an extensive list of supported platforms including .net6. We recommend transitioning as it will receive the most development focus going forward.

Cheers!
