### ISSUE TITLE
Compatibility with Windows 10 Universal Apps

### ISSUE THREAD

**Issue by mjracca** [segmentio/Analytics.Xamarin#8]
I'm trying to use Segement on a UAP app. Should I use this library?

I successfully added it to my project but the things I'm sending aren't showing in the Debugger, either the Schema, after several hours.

**Comment by f2prateek** [comment]
Can you share the logs?

**Comment by mjracca** [comment]
```
Exception thrown: 'System.IO.FileLoadException' in Analytics.dll

**Comment by mjracca** [comment]
Ok, so I tested it in a clean and new project and it works! Something may be wrong with my current project. Thanks!

**Comment by mjracca** [comment]
Do you have any clue why this could be happening?

**Comment by f2prateek** [comment]
Stack trace? When is this happening? Sample code?

**Comment by mjracca** [comment]
Found it! Had an old version of Json.NET, updated and works perfectly :)
Thanks!!

**Comment by f2prateek** [comment]
:+1: let us know if you run into any other issues
