### ISSUE TITLE
Windows UAP overriding Library Name

### ISSUE THREAD

**Issue by mjracca** [segmentio/Analytics.Xamarin#9]
I'm adding Analytics.Xamarin to my UAP app, since I will be using Amplitude. 

What I would like to do is to register the DeviceFamily (Windows.Desktop, Windows.Team, etc), without losing the basic device information (model, manufacturer, etc). 

So, what I tried to change is the "Platform" (["library"]["name"]), but doing that will invalidate all the location information of the user:

![image](https://cloud.githubusercontent.com/assets/3976257/12496763/5632d57e-c076-11e5-8c9a-ba108df6dc12.png)

![image](https://cloud.githubusercontent.com/assets/3976257/12496746/410c33f2-c076-11e5-9cd7-62143485bc87.png)

Any idea on how to set my own Platform?

**Comment by juliette-ruchel** [comment]
Hi @mjracca, could you change the library you are currently using in your UWP app to use the current version of the Analytics.NET library? 
The Analytics.NET library has support for .NET standard 1.3 and 2.0. This means that it works fine with xamarin applications and UWP applications.
